In [ ]:
"""
Pseudocode

path= []
visited_vertices = [false, false, ....] #list of all N points, initialize as false as path path hasnt visited
start = 0 #what vertex to start
visited[start] = true
add start to path

def hamiltonian(path, v): #where v is the current selected vertex
    if path.size() == N: #where N is number of total points
        return true
    for each adjacent_vertex of v:
        if visited[av] == false:
            visited[av] == true
            add av to path
            
            if hamiltonian(path,av):
                return true
                
            #backtracking (if it's surrounded by vertices that are already visited/in the path, go back and delete it, start from previous point)    
            visited[av] = false
            remove av from path
    return false

"""

In [2]:
import networkx as nx
import numpy as np

In [18]:
#graph construction from edges
edges = [(0, 1), (0, 2), (0, 3), (1, 2), (1, 3), (2, 3)]
G = nx.Graph(edges)
print(G.edges())

A = nx.adjacency_matrix(G)
print(A.todense())

#graph construction from adj matrix
A = np.array([[0, 1, 1, 1], [1, 0, 1, 1],
            [1, 1, 0, 1],[1, 1, 1, 0]])
G = nx.from_numpy_matrix(A)
print(G.edges())


[(0, 1), (0, 2), (0, 3), (1, 2), (1, 3), (2, 3)]
[[0 1 1 1]
 [1 0 1 1]
 [1 1 0 1]
 [1 1 1 0]]
[(0, 1), (0, 2), (0, 3), (1, 2), (1, 3), (2, 3)]


In [30]:
def adjList(graph):
    adjList = [[] for _ in range(graph.number_of_nodes())]
    for (src, dest) in graph.edges():
        adjList[src].append(dest)
        adjList[dest].append(src)
    return adjList

In [50]:
print(adjList(G))

[[1, 2, 3], [0, 2, 3], [0, 1, 3], [0, 1, 2]]


In [145]:
def hampath(graph, v, visited, path, c):
    n = graph.number_of_nodes()
    
    if len(path) == n:
        c.extend(path)
#         print(path)
        return
    
    adj_list = adjList(graph)
    
    for w in adj_list[v]:
        if not visited[w]:
            visited[w] = True
            path.append(w)

            hampath(graph, w, visited, path, c)

            visited[w] = False
            path.pop()

In [146]:
#testing with start vertex of 0
startV = 0
path = [startV]
c= []     

visited = [False] * G.number_of_nodes()
visited[startV] = True
        
hampath(G, startV, visited, path, c)

#splitting c into groups of 4 (number of nodes G has)
n=4
final = [c[i * n:(i + 1) * n] for i in range((len(c) + n - 1) // n )]
print(final)

[[0, 1, 2, 3], [0, 1, 3, 2], [0, 2, 1, 3], [0, 2, 3, 1], [0, 3, 1, 2], [0, 3, 2, 1]]


In [154]:
def findallHamPaths(graph):
    n = graph.number_of_nodes()
    allpaths = []
    for startV in range(n):
        path = [startV]
        c = []
        visited = [False] * n
        visited[startV] = True
        
        hampath(graph, startV, visited, path, c)
        final = [c[i * n:(i + 1) * n] for i in range((len(c) + n - 1) // n )]
        allpaths.append(final)
        allpathsflat = [item for sublist in allpaths for item in sublist]
    return allpathsflat

In [158]:
findallHamPaths(G)
# print(len(findallHamPaths(G)))

[[0, 1, 2, 3],
 [0, 1, 3, 2],
 [0, 2, 1, 3],
 [0, 2, 3, 1],
 [0, 3, 1, 2],
 [0, 3, 2, 1],
 [1, 0, 2, 3],
 [1, 0, 3, 2],
 [1, 2, 0, 3],
 [1, 2, 3, 0],
 [1, 3, 0, 2],
 [1, 3, 2, 0],
 [2, 0, 1, 3],
 [2, 0, 3, 1],
 [2, 1, 0, 3],
 [2, 1, 3, 0],
 [2, 3, 0, 1],
 [2, 3, 1, 0],
 [3, 0, 1, 2],
 [3, 0, 2, 1],
 [3, 1, 0, 2],
 [3, 1, 2, 0],
 [3, 2, 0, 1],
 [3, 2, 1, 0]]